#
# Module manifest for module 'SecretsManagement.KeePass'
#
# Generated by: jgrote
#
# Generated on: 2/10/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SecretManagement.KeePass.psm1'

# Version number of this module.
ModuleVersion = '0.9.2'

# Supported PSEditions
CompatiblePSEditions = @('Desktop','Core')

# ID used to uniquely identify this module
GUID = '14f945da-777e-4f2b-9c79-b59287d19478'

# Author of this module
Author = 'Justin Grote'

# Copyright statement for this module
Copyright = '(c) 2021 Justin Grote. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A cross-platform Keepass Secret Management vault extension. See the README.MD in the module for more details.'

# Modules that must be imported into the global environment prior to importing this module
NestedModules = @(
    './SecretManagement.KeePass.Extension/SecretManagement.KeePass.Extension.psd1'
)
RequiredModules = @(
        @{ModuleName = 'Microsoft.Powershell.SecretManagement'; ModuleVersion = '1.1.0' },
        @{ModuleName = 'PSFramework'; ModuleVersion = '1.6.205' }
)
PowershellVersion = '5.1'
FunctionsToExport = @('Register-KeePassSecretVault','Unlock-KeePassSecretVault')
CmdletsToExport   = @()
VariablesToExport = @()
AliasesToExport   = @()
PrivateData = @{
    PSData = @{
        Tags       = 'SecretManagement', 'KeePass', 'SecretVault', 'Vault', 'Secret'
        ProjectUri = 'https://www.github.com/JustinGrote/SecretManagement.KeePass'
        IconUri    = 'https://raw.githubusercontent.com/JustinGrote/SecretManagement.KeePass/main/images/Logo.png'
        Prerelease = ''
        ReleaseNotes = '## [0.9.2] - 2021-08-22
### Minor Updates and Bug Fixes
- ⬆️ SecretManagement 1.1.0 Compatibility (#55)  
    SecretManagement 1.1.0 moves the vault extension into its own runspace and adds a new Unlock-SecretVault mechanism. This adds support for that new operating model.
- 📦 Fix issue with common tests being included in compilation (e277af9)
- 📦 Wrap Public Function Initialization in SourceInit region (2818d4c)
- 🐛 Tests were being included in build process, causing import errors (ab83ff6)
- ⬆️ Microsoft.Powershell.SecretManagement 1.0.0 (11d45c7)
- 🔖 v0.9.1.3 (75d25c3)
- 🐛 UNC Paths incorrectly translated to PSProvider Paths  (#45)  
    Fixes #44

### Other
- Update parameter names in README.MD (#51)  
    * Updated parameter name in README.MD  
    * Updated 2nd parameter name in README.MD
- Add Press Github Actions Support (#46)'
    }
}
}

